# Generated by Django 2.2.11 on 2020-03-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200313_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='new',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
