# Generated by Django 2.2.11 on 2020-03-13 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='new',
        ),
    ]
